### ISSUE TITLE
Support for Unitary Group

### ISSUE THREAD

**Issue by jiahaosu** [Lezcano/expRNN#8]
Hello,

Thanks for your implementation!

I saw that the paper supports optimization over the special orthogonal group and the unitary group. However, I can only find the code for the special orthogonal group in the repo. I wonder if you could also provide the code to optimize over a unitary group. 

Best,

Jiahao

**Comment by lezcano** [comment]
Closing this as this repository is not being maintained,as it says in the readme. See also https://github.com/Lezcano/geotorch/issues/35
